version: 2.1
orbs:
  pulumi: pulumi/pulumi@1.2.0
jobs:
  build:
    docker:
      - image: cimg/go:1.14
    steps:
      - checkout
      - pulumi/login:
          version: 2.0.0
      - run:
          command: |
            echo Create Pulumi file
            echo "config:" >> ~/project/pulumi/Pulumi.dev.yaml
            echo "  aws:region: us-west-2" >> ~/project/pulumi/Pulumi.dev.yaml
            echo "  awsconfig:generic:" >> ~/project/pulumi/Pulumi.dev.yaml
            echo "    accountid: \"$AWS_ACCOUNT_ID\"" >> ~/project/pulumi/Pulumi.dev.yaml
            echo "    sentrydsn: $SENTRY_DSN" >> ~/project/pulumi/Pulumi.dev.yaml
            echo "  awsconfig:tags:" >> ~/project/pulumi/Pulumi.dev.yaml
            echo "    author: retgits" >> ~/project/pulumi/Pulumi.dev.yaml
            echo "    feature: acmeserverless" >> ~/project/pulumi/Pulumi.dev.yaml
            echo "    team: vcs" >> ~/project/pulumi/Pulumi.dev.yaml
            echo "    version: 0.2.0" >> ~/project/pulumi/Pulumi.dev.yaml
            pulumi plugin install resource aws 1.24.0
      - pulumi/update:
          stack: retgits/dev
          working_directory: ~/project/pulumi
          skip-preview: true
workflows:
  version: 2
  deploy:
    jobs:
      - build:
          context: ACMEServerless
